apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pf9-despotify
  namespace: {{ .Values.namespace }}
  {{- if .Values.deployment_labels }}
  labels:
    {{- toYaml .Values.deployment_labels | nindent 4 }}
  {{- end }}
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20
    type: RollingUpdate
  selector:
    matchLabels:
      {{- toYaml .Values.pod_labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.pod_labels | nindent 8 }}
    spec:
      priorityClassName: high-priority
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: pf9-despotify
        image: {{ .Values.despotify_image }}
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NOTICE_URL
          valueFrom:
            configMapKeyRef:
              name: despotify
              key: NOTICE_URL
        - name: SLACK_URL
          valueFrom:
            configMapKeyRef:
              name: despotify
              key: SLACK_URL
        - name: SLACK_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: despotify
              key: SLACK_CHANNEL
        - name: SLACK_USERNAME
          valueFrom:
            configMapKeyRef:
              name: despotify
              key: SLACK_USERNAME
        - name: DETACH_FROM_ASG
          valueFrom:
            configMapKeyRef:
              name: despotify
              key: DETACH_FROM_ASG
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 30
